### PR TITLE
`r_github_packages:` has to be a list

### PR DESCRIPTION
**Pull request by jimhester**
This is why https://travis-ci.org/renozao/NMF/jobs/112031689#L5 failed

### CODE REVIEW

**Comment by renozao** [comment]
Thanks!

**Comment by renozao** [comment]
Anyway to specify a branch: renozao/pkgmaker/develop

**Comment by jimhester** [comment]
Yes, 
```yaml
r_github_packages: 
  - renozao/pkgmaker@develop
```

**Comment by renozao** [comment]
I tried this indeed and it worked. 
Now I need to deal with real error in my code.
Great thanks

**Pull request merged**
